server:
    port: 3008
management:
  port: 4008
  security:
    enabled: false
eureka:
    client:
      service-url:
         defaultZone: http://user:123456@localhost:8762/eureka/
    instance:
      metadata-map:
         management.port: ${management.port}
spring:
  application:
    name: account-web
  redis:
    host: localhost
    port: 6379
  thymeleaf:
    cache: false
  mvc:
    static-path-pattern: /static/**
feign:
  hystrix:
    enabled: true

info:
  domain: localhost
  domain.version: 1.0
  account.login.url: http://${info.domain}:3008/login/index
  account.logout.url: http://${info.domain}:3008/logout
  buyer.domain: http://${info.domain}:3009/buyer/index
  seller.domain: http://${info.domain}:3009/seller/index
