server:
    port: 3008
management:
  port: 4008
  security:
    enabled: false
eureka:
    client:
      service-url:
         defaultZone: http://user:123456@localhost:8762/eureka/
    instance:
      metadata-map:
         management.port: ${management.port}
spring:
  application:
    name: test-web
feign:
  hystrix:
    enabled: true